eureka:
  client:
    eureka-server-port: 8761
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    appname: order-service


server:
  port: 0
  servlet:
    context-path: /order

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: divan
    password: pass
    driver-class-name: org.postgresql.Driver
  application:
    name: order-service
