#spring:
#  data:
#    mongodb:
#      host: 27017

eureka:
  instance:
    appname: product-service
  client:
    eureka-server-port: 8761
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: product-service

server:
  port: 0
  servlet:
    context-path: /product