eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: eureka-server
  server:
    renewal-percent-threshold: [0.0,1.0]

spring:
  application:
    name: eureka-server
server:
  port: 8761
